name: Build and Deploy GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy-gh-pages:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy GitHub Pages
        uses: glnk-dev/webapp@v0.1.1
        with:
          GLNK_USERNAME: gcp
          GLNK_PUBLIC_URL: https://gcp.glnk.dev/
